// The tactical test suite — docs/engine/06-MEASUREMENT-AND-LEVELS.md part
// one, §2: "positions with a known best move, scored as how many does the
// engine find in N seconds. It catches regressions that match play is too
// noisy to see, and it runs in seconds rather than hours."
//
// `data/tactics.json` is generated by `generate-tactics.ts` from two of the
// doc's three sources (defensive positions and race positions; the third —
// endgame positions from the tablebase — waits on 05-LEARNING-AND-TABLES.md).
// The shape mirrors packages/engine/src/data/tutorial.json — fen plus
// solution(s), graded by comparing `moveToText` — which is the "repo already
// has the right shape for this" the doc points at.

import { fromFen, getVariant, moveToText } from '@sps/engine';
import type { VariantId } from '@sps/engine';
import { chooseMove } from '@sps/ai';
import type { EngineConfig } from './match.js';
import tacticsData from '../data/tactics.json' with { type: 'json' };

export interface TacticPuzzle {
  id: string;
  category: 'defensive' | 'race';
  variant: VariantId;
  fen: string;
  /** Any one of these counts as solved — a defensive puzzle usually has more
   *  than one way to save the piece. */
  solutions: string[];
  note: string;
}

export const TACTIC_PUZZLES: readonly TacticPuzzle[] = tacticsData.puzzles as TacticPuzzle[];

export interface TacticOutcome {
  id: string;
  category: TacticPuzzle['category'];
  solved: boolean;
  played: string;
}

interface CategoryTally {
  total: number;
  solved: number;
  rate: number;
}

export interface TacticsResult {
  level: string;
  total: number;
  solved: number;
  rate: number;
  byCategory: Record<TacticPuzzle['category'], CategoryTally>;
  outcomes: TacticOutcome[];
}

function rate(part: number, whole: number): number {
  return whole === 0 ? 0 : Number((part / whole).toFixed(4));
}

/**
 * Runs `level` against every puzzle in `puzzles` (default: the whole
 * committed suite) and reports the solve rate overall and per category.
 *
 * `seed` matters for a level with jitter (Easy, or a custom config): this
 * checks the one move `chooseMove` actually returns for that seed, which is
 * what a player would see — not whether every move the jitter could have
 * produced would also have solved it, which is a different and stronger
 * claim.
 */
export function runTactics(
  level: EngineConfig,
  puzzles: readonly TacticPuzzle[] = TACTIC_PUZZLES,
  seed = 1,
): TacticsResult {
  const outcomes: TacticOutcome[] = [];
  const totals: Record<TacticPuzzle['category'], { total: number; solved: number }> = {
    defensive: { total: 0, solved: 0 },
    race: { total: 0, solved: 0 },
  };

  for (const puzzle of puzzles) {
    const variant = getVariant(puzzle.variant);
    const state = fromFen(puzzle.fen, variant);
    const { move } = chooseMove(state, level, seed);
    const played = moveToText(state, move);
    const solved = puzzle.solutions.includes(played);

    outcomes.push({ id: puzzle.id, category: puzzle.category, solved, played });
    totals[puzzle.category].total++;
    if (solved) totals[puzzle.category].solved++;
  }

  const total = puzzles.length;
  const solved = outcomes.filter((outcome) => outcome.solved).length;

  return {
    level: typeof level === 'string' ? level : 'custom',
    total,
    solved,
    rate: rate(solved, total),
    byCategory: {
      defensive: { ...totals.defensive, rate: rate(totals.defensive.solved, totals.defensive.total) },
      race: { ...totals.race, rate: rate(totals.race.solved, totals.race.total) },
    },
    outcomes,
  };
}
